function [ub, lb] = m_bounds(mods)
%% Function Purpose:
% A simple function to set up boundary conditions for the optimizer.

% Created by Andrew Meyer
% Last modified: 10/29/2024
ub = zeros(1,length(mods));
lb = ub;
pairs = dictionary('C_SA', {[-2 2]}, ...
    'C_PA', {[-2 2]}, ...
    'C_SV', {[-2 2]}, ...
    'C_PV', {[-2 2]}, ...
    'R_SA', {[-1 1]}, ...
    'R_tSA', {[-1 1]}, ...
    'R_PA', {[-1 1]}, ...
    'R_tPA', {[-1 1]}, ...
    'R_t_o', {[-1 1]}, ...
    'R_t_c', {[-1 1]}, ...
    'R_p_o', {[-1 1]}, ...
    'R_p_c', {[-2 2]}, ...
    'R_m_o', {[-1 1]}, ...
    'R_m_c', {[-1.3 1.3]}, ...
    'R_a_o', {[-1 1]}, ...
    'R_a_c', {[-1.3 1.3]}, ...
    'k_pas_LV', {[-1 1]}, ...
    'k_act_LV', {[-1 1]}, ...
    'k_pas_RV', {[-1 1]}, ...
    'k_act_RV', {[-1 1]}, ...
    'Amref_LV', {[-0.3 0.3]}, ...
    'Amref_RV', {[-0.3 0.3]}, ...
    'Vw_LV', {[-0.3 0.3]}, ...
    'Vw_RV', {[-0.3 0.3]}, ...
    'tau_TR', {[-0.25 0.25]}, ...
    'tau_TS', {[-0.25 0.25]}, ...
    'R_Veins', {[-1.3 1.3]}, ...
    'K1',{[-1 0.6]},...
    'expPeri',{[-1 1.25]},...
    'LvSepR',{[-0.06 0.06]});
for i = 1:length(mods)
    bounds_i = pairs(mods{i});
    lb(i) = bounds_i{1}(1);
    ub(i) = bounds_i{1}(2);
end
end