function [ub, lb] = m_bounds(mods)
%% Function Purpose:
% A simple function to set up boundary conditions for the optimizer.

% Created by Andrew Meyer
% Last modified: 10/29/2024
ub = zeros(1,length(mods));
lb = ub;
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
pairs = dictionary('C_SA', {[0.1 10]}, ...
                   'C_SV', {[0.1 10]}, ...
                   'C_PA', {[0.1 10]}, ...
                   'C_PV', {[0.1 10]}, ...
                   'R_SA', {[0.1 10]}, ...
                   'R_tSA', {[0.15 15]}, ...
                   'R_PA', {[0.1 10]}, ...
                   'R_tPA', {[0.15 15]}, ...
                   'R_t_o', {[0.1 10]}, ...
                   'R_t_c', {[0.1 10]}, ...
                   'R_p_o', {[0.1 10]}, ...
                   'R_p_c', {[0.05 20]}, ...
                   'R_m_o', {[0.1 10]}, ...
                   'R_m_c', {[0.05 20]}, ...
                   'R_a_o', {[0.1 10]}, ...
                   'R_a_c', {[0.05 20]}, ...
                   'k_act', {[0.2 5]}, ...
                   'k_pas_LV', {[0.02 500]}, ...
                   'k_act_LV', {[0.02 500]}, ...
                   'k_pas_RV', {[0.02 500]}, ...
                   'k_act_RV', {[0.02 500]}, ...
                   'Amref_LV', {[1 1]}, ...
                   'Amref_SEP', {[1 1]}, ...
                   'Amref_RV', {[1 1]}, ...
                   'Vw_LV', {[0.33 3]}, ...
                   'Vw_SEP', {[0.33 3]}, ...
                   'Vw_RV', {[0.33 3]}, ...
                   'RAV0u', {[1 1]}, ...
                   'LAV0u', {[1 1]}, ...
                   'V0u_coeff', {[1 1]}, ...
                   'LEa', {[1 1]}, ...
                   'REa', {[1 1]}, ...
 ...
 'V0c_coeff', {[1 1]}, ...
                   'LAV0c', {[1 1]}, ...
                   'RAV0c', {[1 1]}, ...
                   'LAV1c', {[1 1]}, ...
                   'RAV1c', {[1 1]}, ...
                   'LEp', {[1 1]}, ...
                   'REp', {[1 1]}, ...
                   'Pc', {[1 1]}, ...
                   'R_atria', {[0.05 20]}, ...
                   'R_RA', {[0.05 20]}, ...
                   'R_LA', {[0.05 20]}, ...
                   'LvSepR',{[0.85 1.15]},...
                   'K_P', {[0.33 3]}, ...
                   'Vh0', {[1 1]}, ...
                   'B_P',{[0.5 20]});
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
pairs = dictionary('C_SA', {[-2 2]}, ...
    'C_PA', {[-2 2]}, ...
    'C_SV', {[-2 2]}, ...
    'C_PV', {[-2 2]}, ...
    'R_SA', {[-1 1]}, ...
    'R_tSA', {[-1 1]}, ...
    'R_PA', {[-1 1]}, ...
    'R_tPA', {[-1 1]}, ...
    'R_t_o', {[-1 1]}, ...
    'R_t_c', {[-1 1]}, ...
    'R_p_o', {[-1 1]}, ...
    'R_p_c', {[-2 2]}, ...
    'R_m_o', {[-1 1]}, ...
    'R_m_c', {[-1.3 1.3]}, ...
    'R_a_o', {[-1 1]}, ...
    'R_a_c', {[-1.3 1.3]}, ...
    'k_pas_LV', {[-1 1]}, ...
    'k_act_LV', {[-1 1]}, ...
    'k_pas_RV', {[-1 1]}, ...
    'k_act_RV', {[-1 1]}, ...
    'Amref_LV', {[-0.3 0.3]}, ...
    'Amref_RV', {[-0.3 0.3]}, ...
    'Vw_LV', {[-0.3 0.3]}, ...
    'Vw_RV', {[-0.3 0.3]}, ...
    'tau_TR', {[-0.25 0.25]}, ...
    'tau_TS', {[-0.25 0.25]}, ...
    'R_Veins', {[-1.3 1.3]}, ...
    'K1',{[-1 0.6]},...
    'expPeri',{[-1 1.25]},...
    'LvSepR',{[-0.06 0.06]});
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
for i = 1:length(mods)
    bounds_i = pairs(mods{i});
    lb(i) = bounds_i{1}(1);
    ub(i) = bounds_i{1}(2);
end
end